baseURL = "https://martinfehrensen.de/"
languageCode = "de"
title = "Martin Fehrensen"
[pagination]
  pagerSize = 10
enableRobotsTXT = true

[params]
  description = "Martin Fehrensen: Journalist & Speaker. Gründer Social Media Watchblog: Newsletter zum Wandel der digitalen Öffentlichkeit."
  footerText = 'Auf dieser Website werden keine Daten gesammelt.'
  ogImage = "/img/mf.jpg"

[menu]
  [[menu.main]]
    name = "Über"
    url  = "/ueber/"
    weight = 1
  [[menu.main]]
    name = "Speaking"
    url  = "/speaking/"
    weight = 2
  [[menu.main]]
    name = "Newsletter"
    url  = "/newsletter/"
    weight = 3

[taxonomies]
  tag = "tags"

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "index"
    isPlainText = true

[outputs]
  home = ["HTML", "RSS"]
